### ISSUE TITLE
Accordions

### ISSUE THREAD

**Issue by antoninadert** [papercss/papercss#110]
It would be a nice addition to offer paper accordions.

**Comment by TotomInc** [comment]
It would be a nice feature, just a small reminder that it must be done without any Javascript. It looks like there are some ways to do pure CSS accordion [according to this codepen](https://codepen.io/raubaca/pen/PZzpVe). It's based on `:checked` state of hidden checkbox/radios input. About the styling, I think we can keep something super simple based of [Bootstrap accordion style](https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example).

**Comment by afzalsayed96** [comment]
I've been trying to implement this feature already since last few days and I am facing the following problems.
Collapsibles can be implemented with checkbox where multiple sections can be expanded simultaneously. For accordions like this: [http://materializecss.com/collapsible.html] which should allow expanding only one section at a time get's messy, if we use radio buttons we cannot uncheck a checked (or expanded) section using only CSS.
Finally using CSS animations (transition or keyframes) cause the section to animate even on page load which cannot be prevented again without JS :(

Here's a demo what I implemented

![ezgif-2-0927f918d0](https://user-images.githubusercontent.com/14029371/33956162-bd77f412-e063-11e7-9168-36ffd3efc1ce.gif)

**Comment by rhyneav** [comment]
Merged in #113 :D
