### ISSUE TITLE
Normalize.css Dependency

### ISSUE THREAD

**Issue by rhyneav** [papercss/papercss#26]
Currently, [normalize.css](https://github.com/necolas/normalize.css/) is a dev dependency which will cause some problems when packaging for npm. It is also being imported via relative paths, which may also cause issues on npm. 

normalize.css either needs to be
- Added instead to dependencies in package.json
- Or added as a git submodule

The import in src/styles.less will then need to be changed to no longer be relative.

**Comment by TotomInc** [comment]
Hey I'm currently working on this one. Since our gulp process `.less`files, I will make the move to [normalize.less](https://www.npmjs.com/package/normalize.less), which is obviously a less version of normalize.css. I'll update the gulp file to import normalize.css (using `__dirname`) and remove the hard-coded dependency in `styles.less`.

**Comment by TotomInc** [comment]
I think the best way is to create a custom `reset.less` file including normalize.css with other custom reset code. Include this file on the top of `styles.less`.

**Comment by rhyneav** [comment]
That makes sense. We could import the normalize.less as well as include the boxreset.less styles there too to keep it all in one spot.

**Comment by TotomInc** [comment]
You can look [here](https://github.com/papercss/papercss/blob/separate-components/src/reset.less), I have included normalize.less in a core file of papercss. This allow an easier integration with packages that uses papercss. I'll also add or remove boxreset.less

**Comment by rhyneav** [comment]
Ah perfect. We can just keep the boxreset as an import to styles.less if that's easier than including it within the reset file.

**Comment by TotomInc** [comment]
Well actually the separate-components branch is working well except for unit tests. I don't really understand this part, if @Fraham can take a look at this it would be very cool.

Once unit tests are fixed, I'll merge separate-components into develop, and we should prepare a release (1.2.1 or 1.3.0) because those changes are very important (it modularize papercss and allow everyone to implement it in their project how they want).

**Comment by rhyneav** [comment]
Absolutely. With the added features, it will make sense to pop out 1.3.0

**Comment by Fraham** [comment]
Unit test issue sorted

**Comment by TotomInc** [comment]
Well I think I can merge separate-components into develop ASAP. It looks stable and unit test are fixed.

**Comment by TotomInc** [comment]
Closed since #114 have been merged. @rhyneav you can prepare 1.3.0?

**Comment by rhyneav** [comment]
You got it @TotomInc! I'll get that out today or tomorrow at the latest.
