### ISSUE TITLE
Display modal in front of nav

### ISSUE THREAD

**Issue by mef** [papercss/papercss#268]
Currently, the modal component has  a `z-index` of 12, whereas the `z-index` of the nav component is 100.

This makes the modal to be displayed _below_ navbar. This is especially problematic on devices with smaller screen, where the modal panel's content might be partly covered by the nav.

Should the modal's z-index be increased to 101?

**Comment by koester** [comment]
Thanks for opening an issue and yes, your proposed solution is right. 

I would suggest to increase the z-index of the modal even higher than 101, probably around 200, just so we have some room  for other components later on. The Modal should have the highest z-index of any component, since the use case is to overlap the whole page.

Feel free to open a PR with your proposed change :)
