### ISSUE TITLE
Supports only english fonts :(

### ISSUE THREAD

**Issue by spapas** [papercss/papercss#59]
Hello, the fonts that are used do not support other languages except english. More specifically, I wanted to use papercss for a project in greek but the fonts that are substituted when using greek are really ugly. 

Here's how the default styles are displayed when I write greek:

![papercss](https://user-images.githubusercontent.com/3911074/33116661-4634857e-cf6e-11e7-95dd-997b657eeab4.png)

Can you propose any fonts that *do* support greek and match nice with the overall style?

TIA !

**Comment by Kaperskyguru** [comment]
ok... nice for the feedback

**Comment by TotomInc** [comment]
Currently PaperCSS use 2 fonts: [Patrick Hand SC](https://fonts.google.com/specimen/Patrick+Hand+SC?selection.family=Patrick+Hand+SC) for things like headers, and [Neucha](https://fonts.google.com/specimen/Neucha?selection.family=Neucha). In the `fonts.less` [we import the fonts from Google Fonts](https://github.com/rhyneav/papercss/blob/f3ee817270996967de8a4e4aa6b252ae0c2bd0cc/src/fonts.less#L1). We didn't include greek fonts because it would make the download of the font-size heavier and longer. If some people want to use specific fonts, it should be done in their side.

**Comment by spapas** [comment]
The problem is that neither of these fonts not support greek... Could you propose other fonts to use instead?

**Comment by TotomInc** [comment]
We are open to any suggestions about fonts. If you find one that have greek support but also other language support, just let us know or make a PR with the new font!

**Comment by spapas** [comment]
Unfortunately google fonts doesn't have any handwriting fonts that support greek :( https://fonts.google.com/?selection.family=Neucha&subset=greek&category=Handwriting

**Comment by rhyneav** [comment]
Sorry about that @spapas! I would recommend dropping in Neucha as @amanbayev mentioned. That seems like a good fix for this.

**Comment by spapas** [comment]
Unfortunately the Neucha font doesn't support greek characters either :( If anybody could recommend a font that supported greek fonts and was compatible with the papercss style I'd be grateful!

**Comment by rhyneav** [comment]
@spapas here's [a list of fonts that support Greek characters](https://www.fontsquirrel.com/fonts/list/language/greek). Hope this helps!

**Comment by spapas** [comment]
Interesting list thanks !
